//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CropRecommendationWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogId { get; set; }
        public string UserId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string IpAddress { get; set; }
        public string OtherInfo { get; set; }
    
        public virtual User User { get; set; }
    }
}
